// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzcgxWxy5ro5UiWUNmVWkla9pi-3qKHeQ',
    appId: '1:313803556092:web:3178439cc299ee1b3d0379',
    messagingSenderId: '313803556092',
    projectId: 'internship-6d38b',
    authDomain: 'internship-6d38b.firebaseapp.com',
    storageBucket: 'internship-6d38b.appspot.com',
    measurementId: 'G-ELB30V7BXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSdapWpgGjx31bBPPk5WNl9vZV7Zpwveo',
    appId: '1:313803556092:android:34753fffa1a9a95e3d0379',
    messagingSenderId: '313803556092',
    projectId: 'internship-6d38b',
    storageBucket: 'internship-6d38b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmxr70v4xxFhtEWFpk2BV0cxcK9y35kv8',
    appId: '1:313803556092:ios:66536fa826b3b7923d0379',
    messagingSenderId: '313803556092',
    projectId: 'internship-6d38b',
    storageBucket: 'internship-6d38b.appspot.com',
    iosBundleId: 'com.example.proj',
  );
}
